[tool.poetry]
name = "poc-liveness-app"
version = "0.1.0"
description = "A Streamlit application project"

[tool.poetry.dependencies]
python = "^3.7"
streamlit = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"